export const ORDERS_CONNECT = 'ORDERS_CONNECT';
export const ORDERS_DISCONNECT = 'ORDERS_DISCONNECT';
export const ORDERS_CONNECTING = 'ORDERS_CONNECTING';
export const ORDERS_OPEN = 'ORDERS_OPEN';
export const ORDERS_CLOSE = 'ORDERS_CLOSE';
export const ORDERS_MESSAGE = 'ORDERS_MESSAGE';
export const ORDERS_ERROR = 'ORDERS_ERRORs';