export const ADD_BURGER_INGREDIENTS = 'ADD_BURGER_INGREDIENTS';
export const REMOVE_BURGER_INGREDIENTS = 'REMOVE_BURGER_INGREDIENTS';
export const SET_MODAL_INGREDIENT = 'SET_MODAL_INGREDIENT';
export const REMOVE_MODAL_INGREDIENT = 'REMOVE_MODAL_INGREDIENT';
export const CHANGE_ORDER = 'CHANGE_ORDER';
export const CHANGE_BUNS_TAB_POSITION = 'CHANGE_BUNS_TAB_POSITION';
export const CHANGE_SAUCES_TAB_POSITION = 'CHANGE_BUNS_TAB_POSITION';
export const CHANGE_MAINS_TAB_POSITION = 'CHANGE_BUNS_TAB_POSITION';