export const ADD_BURGER_INGREDIENTS = 'ADD_BURGER_INGREDIENTS';
export const REMOVE_BURGER_INGREDIENTS = 'REMOVE_BURGER_INGREDIENTS';
export const SET_MODAL_INGREDIENT = 'SET_MODAL_INGREDIENT';
export const REMOVE_MODAL_INGREDIENT = 'REMOVE_MODAL_INGREDIENT';