export const CHANGE_BUNS_TAB_POSITION = 'CHANGE_BUNS_TAB_POSITION';
export const CHANGE_SAUCES_TAB_POSITION = 'CHANGE_SAUCES_TAB_POSITION';
export const CHANGE_MAINS_TAB_POSITION = 'CHANGE_MAINS_TAB_POSITION';